{% set name = "yabadaba" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a61263deac2a773146d72767a5f2a21f2e8c9d18d49c5db240348b90f4a9edf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - lxml
    - datamodeldict
    - ipython
    - numpy
    - pandas
    - cdcs >=0.1.5
    - pymongo

test:
  imports:
    - yabadaba
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/yabadaba
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: An abstraction layer for NoSQL databases
  description: |
    Yay, a base database! An abstraction layer allowing for common interactions
    with Mongo, CDCS and local directory databases and records.
  doc_url: https://github.com/usnistgov/yabadaba
  dev_url: https://github.com/lmale99/yabadaba

extra:
  recipe-maintainers:
    - lmhale99
